version: 2
general:
  branches:
    only:
      master
jobs:
  build:
    docker:
      - image: circleci/node:8
    branches:
      only:
      - master
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test -- --coverage
      - run: # Production build
          name: Make a production build
          command: npm run build

      - run: #Deploy to Firebase Hosting
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
