version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test -- --coverage

      - run: # Deploy to Firebase
          name: Deploy Master branch to Firebase Hosting
#          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
#  deploy-job:
#    docker:
#    - image: my-image-version-tag
#    working_directory: /tmp/my-project
#    steps:
#    - run:
#        name: Deploy Master to Firebase
#        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
#
#    workflows:
#      version: 2
#
#      -deploy:
#        jobs:
#        - build-job
#        - deploy-job:
#            requires:
#            - build-job
#            filters:
#              branches:
#                only: master
